ALTER TABLE loans
ALTER COLUMN loan_amount TYPE DOUBLE PRECISION USING loan_amount::DOUBLE PRECISION;

ALTER TABLE loans
ALTER COLUMN interest_rate TYPE DOUBLE PRECISION USING interest_rate::DOUBLE PRECISION;
